### ISSUE TITLE
CUDA Lite needs reloading fpga image after each run

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_f1#300] opened 2019-06-19 23:00 UTC
After each cuda lite test run, the program leaves fpga in a bad state, causing the next run to hang (tiles are unresponsive) 
Multiple tile group executions and kernel executions can run inside one <device_init  -  device_finish> scope, but not inside multiple scopes one after another. 
TODO:
    - create a regression test that reproduces the issue in one program 
    - Test in cosim
    - Fix

**Comment by sampsyo** [comment] 2019-06-19 23:02
We're running into this too. It would be awesome to be able to run multiple programs without resetting the FPGA!

**Comment by drichmond** [comment] 2019-06-19 23:28
Yeah, this is a high-priority bug 😬

**Comment by taylor-bsg** [comment] 2019-06-21 03:47
Do you guys use FPGA style resets in the FPGA code? Is there a dependence
on the FPGA resetting state via bitstream?

Code like:

logic foo=1

Would do that.

Unless the FPGA tools handle this reset case in a way that is not obvious
to me.

**Comment by drichmond** [comment] 2019-06-21 17:37
Not that I know of.

**Comment by drichmond** [comment] 2019-06-21 17:37
@leonardxiang can you comment?

**Comment by drichmond** [comment] 2019-06-25 19:59
It appears that this has been solved in the FPU branch - and it was an issue with load reservation instructions. @max-ruttenberg found the source of the issue, Borna found the behavior in simulation, but by the time we root caused it it had been solved in the FPU branch. 

@tommydcjung Can you comment on what may have been the cause and solution? @max-ruttenberg and @bornaehsani Can chip in as necessary.

**Comment by drichmond** [comment] 2019-07-03 16:36
Addressed in #325

**Closed by drichmond** 2019-07-03 16:36 UTC
Labels: Bug, CUDA-Lite
