### ISSUE TITLE
Simple CUDA-Lite example that worked on v1.0.0 hangs on v1.0.2

### ISSUE THREAD

**Issue by sampsyo** [bespoke-silicon-group/bsg_f1#303] opened 2019-06-20 15:17 UTC
Hi, folks! I'm hoping you might be able to help me track down a problem that I've been beating my head against for a while.

I wrote this really simple CUDA-Lite program (consisting of a `host.c` and a device `noop.c`):
https://github.com/cucapra/hb-examples/tree/compat-v1.0.2/dummy

The essence of the problem is that this works fine on our Bladerunner v1.0.0 image (ami-0c6849749f4551621) but not on our v1.0.2 image (ami-09b8871cf40279e0f). The failure mode is a hang in `hb_mc_device_tile_groups_execute`—this call runs forever and never returns.

You'll see that the device code consists of [a single line](
https://github.com/cucapra/hb-examples/blob/6766f0b6b708f917b6e61dec418295016999e561/dummy/noop.c#L21):

```c
*val = 0;
```

Here, `val` is an `int32_t` pointer passed from the host, which uses `hb_mc_device_malloc` to allocate one word. Critically, if you comment out this one line, everything works fine and the kernel exits normally.

Other contingencies:

- Yes, I'm resetting the FPGA before every run to work around #300.
- I've dumped the `eva_t` that comes from the malloc call and it looks like a real address.

I'm at a loss to see what's going wrong here. Do any of you have a wild guess that might help?

**Comment by drichmond** [comment] 2019-06-20 15:22
Yeah, this seems like an issue. You've only run on F1?

**Comment by sampsyo** [comment] 2019-06-20 15:22
Yes.

**Comment by drichmond** [comment] 2019-06-20 15:22
@bornaehsani @save-buffer Can one of pull @sampsyo's failing test into cosim?

**Comment by bornaehsani** [comment] 2019-06-24 04:44
Hi @sampsyo , terribly sorry for the late reply. 
I've ported this test to the bsg_f1 and bsg_manycore repository. Unfortunately I haven't been able to reproduce the bug, it doesn't occur for me.
If you checkout to the "cuda_dram_tests" branch on both bsg_f1 and bsg_manycore repositories, I have added three tests in regards to this issue: 
    - test_dram_host_allocated: Similar to your test, the host allocates a word on DRAM and passes the address as input argument, the tiles write a value to it and the host compares against the expected value. --> Test passes F1 on both v1.0.0 and v1.0.2
    - test_dram_device_allocated: I took this a bit further and added a similar test, in which the tiles allocate an array in DRAM and each tiles fills a portion of it. The origin tile then writes the address of the array, in another location who's address has been passed to tile's kernel as input argument. The host then copies the array from device DRAM into host dram and checks the values. --> Test passes F1 on both v1.0.0 and v1.0.2
    - test_noop: As I wasn't able to reproduce the bug, I copied the exact text in your code in this test to make sure I'm not doing anything differently than your code. This test is similar to test_dram_host_allcoated in functionality. --> Test passes both F1 and COSIM on both v1.0.0 and v1.0.2 

I'm not exactly sure why the test is failing for you, but can you please give these tests a try and let me know if they pass for you on F1? (if they don't perhaps we're doing something differently in setting up the environments )

**Comment by sampsyo** [comment] 2019-06-25 02:45
Weird!! Thanks so much for following up (and no worries). I’ll try the tests out soon, after I’m home from ISCA.

**Comment by bornaehsani** [comment] 2019-06-25 04:01
Sure no problem, enjoy the conference! 
By the way, the biggest change from v1.0.0 to v1.0.2 was the linker script in the bsg_manycore repo, I didn't see any custom linker scripts in your repo so I assume you're using the ones in the bsg_manycore repo, but if that is not the case you might want to make sure your linker scripts match the ones in the v1.0.2 bsg_manycore/software/spmd/common/ directory.

**Comment by drichmond** [comment] 2019-07-08 17:24
@sampsyo Do you know if this is fixed in v3.0.6?

**Comment by bornaehsani** [comment] 2019-07-08 21:46
The refactored DRAM regression tests are added to the master branch on bsg_f1 in PR #336. All tests pass in the v3.0.6. @sampsyo if the issue is solved in your local workspace we can go ahead and dismiss this issue. Let us know!

**Comment by sampsyo** [comment] 2019-07-11 13:41
Thank you for looking into this, y'all! This does indeed seem to have gone away in v3.0.6. :tada:

**Closed** 2019-07-11 13:42 UTC
Labels: Bug, CUDA-Lite
