### ISSUE TITLE
-lfpga_mgmt missing

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_f1#450] opened 2019-11-06 06:40 UTC
I'm installing bsg_bladerunner from scratch, and this library seems to be not found.

**Comment by drichmond** [comment] 2019-11-06 13:22
In cosimulation?

**Comment by drichmond** [comment] 2019-11-06 21:21
I'm going to close this for now. The cause seems to be that `make build` was run in libraries to build libbsg_manycore_runtime.so before running `make regression`. Running `make build` in libraries assumes that the user is building (and subsequently installing) on an F1 instance where libfpga_mgmt.so is already installed in /usr/lib. However, in Cosimulation, we build libfpga_mgmt.so and libbsg_manycore_runtime.so ourselves, and we provide linker flags to redirect away from /usr/lib.

So Tommy's error seems to be because the .o files for libbsg_manycore_runtime were built assuming that libfpga_mgmt.so was in /usr/lib (which failed). Then, in cosimulation, those .o files didn't need to rebuilt, and they failed again for the same reason above.

**Comment by drichmond** [comment] 2019-11-06 21:22
I've asked Tommy to provide feedback on the documentation, if there was a specific place that was unclear.

**Closed by drichmond** 2019-11-06 21:21 UTC
